### ISSUE TITLE
buildrelease fails with  "The current workspace is not clean."

### ISSUE THREAD

**Issue by matyasatfp** [kercheval/GradleCMPlugin#30]
I am testing your plugin, my config looks like:  

    buildversiontag {
        onlyifclean = false // uncomment if modifying this script and testing the code
     }
     buildreleaseinit {
         mainlinebranch = 'master'
         releasebranch = 'master'
        onlyifclean = false // uncomment if modifying this script and testing the code
    }

but the buildrelease task fails with "The current workspace is not clean." Since the build.gradle is part of the repo, I can only test it with I commit (my untested) build.gradle file.

**Comment by kercheval** [comment]
Commits and uploads will not occur if the workspace is not clean.  I would recommend you add the build.gradle file to the .gitignore file while doing this type of testing to avoid the issue completely.

**Comment by matyasatfp** [comment]
in this case the .gitignore file will be dirty..

**Comment by kercheval** [comment]
Yes, some commit will be required for testing these types of changes if you are working with the release plugin.
