### ISSUE TITLE
GradleCMPlugin does not work in shared file

### ISSUE THREAD

**Issue by isobretatel** [kercheval/GradleCMPlugin#31]
I am trying to apply common code that uses GradleCMPlugin:

file common/gradlecm.gradle:

```
buildscript {
    repositories {
        mavenCentral()
        maven { url 'http://kercheval.org/mvn-repo/releases' }
    }

    dependencies { classpath("org.kercheval:GradleCMPlugin:+") }
}

apply plugin: org.kercheval.gradle.buildvcs.BuildVCSPlugin
apply plugin: org.kercheval.gradle.buildinfo.BuildInfoPlugin
apply plugin: org.kercheval.gradle.buildrelease.BuildReleasePlugin
apply plugin: org.kercheval.gradle.buildversion.BuildVersionPlugin
apply plugin: org.kercheval.gradle.gradlecm.GradleCMPlugin
```

In my build.gradle file:

`apply from: rootProject.file('common/gradlecm.gradle')
`

I am getting error:

> Failed to apply plugin [class 'org.kercheval.gradle.buildinfo.BuildInfoPlugin'] Plugin with id 'buildvcs' not found.

I found Gradle bug report from 2012: http://issues.gradle.org/browse/GRADLE-2136

It looks like GradleCM plugins reference each other by ID: https://github.com/kercheval/GradleCMPlugin/blob/master/src/main/java/org/kercheval/gradle/gradlecm/GradleCMPlugin.java

GradleCM plugins should reference each other by full class name.

**Comment by kercheval** [comment]
Merged https://github.com/kercheval/GradleCMPlugin/pull/32

**Comment by kercheval** [comment]
Merged PR published.

Thanks for the updates!
